version: '3.3'

services:
   db:
     image: mysql:5.7
     container_name: mysql
     volumes:
       - db_data:/var/lib/mysql
     networks:
      - app-network
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
   
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     container_name: wordpress
     volumes:
      - wordpress_data:/var/www/html
     networks:
       - app-network
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
   

   php:
     image: php:7-fpm
     container_name: php-fpm


volumes:
  db_data: {}
  wordpress_data: {}
networks:
  app-network:
    driver: bridge   
